version: "3.8"
services:
  java-be:
    build:
      context: ./hospital
    ports:
      - 8080:8080
    networks:
      - app-network

  node-api:
    build:
      context: ./node-api
    ports:
      - 4000:4000
    environment:
      - PORT = 4000
      - JAVA_BACKEND_URL = http://java-be:8080/api/v1
    networks:
      - app-network
    depends_on:
      - java-be

  react-fe:
    build:
      context: ./react-fe
    ports:
      - 3000:3000
    environment:
      - NODE_BACKEND_URL = http://node-api:4000/api/v1
    depends_on:
      - node-api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
